// <auto-generated />
using System;
using BookLibraryNew;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookLibraryNew.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookLibraryNew.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Damilare oladele",
                            Genre = "Asian",
                            PublishYear = "2024",
                            Title = "Eternal secred king"
                        },
                        new
                        {
                            Id = 2,
                            Author = "James wood",
                            Genre = "Cultivation",
                            PublishYear = "2023",
                            Title = "Legend of swordsMan"
                        },
                        new
                        {
                            Id = 3,
                            Author = "muller james",
                            Genre = "Cultivation",
                            PublishYear = "2023",
                            Title = "Walker of Worlds"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Ibrahim Oloto",
                            Genre = "Cultivation",
                            PublishYear = "2023",
                            Title = "Emperor Dominations"
                        });
                });

            modelBuilder.Entity("BookLibraryNew.Models.Book", b =>
                {
                    b.HasOne("BookLibraryNew.Models.Book", null)
                        .WithMany("books")
                        .HasForeignKey("BookId");
                });

            modelBuilder.Entity("BookLibraryNew.Models.Book", b =>
                {
                    b.Navigation("books");
                });
#pragma warning restore 612, 618
        }
    }
}
